### PR TITLE
[FIX] ANN Predictor alleles mismatching

### PR DESCRIPTION
**Pull request by Zethson**
Dear @b-schubert and @christopher-mohr ,

@christopher-mohr made me aware that the predictors are not quite working as expected.
This likely happened when I fixed the allele names and then tested the implementation with an old cached version or something.

Anyways - it should now be in a working state.

I tested it with 

```
#!/usr/bin/env python

from Fred2.EpitopePrediction import EpitopePredictorFactory
from Fred2.Core.Allele import Allele
from Fred2.Core.Peptide import Peptide

predictor = EpitopePredictorFactory("mhcnuggets-class-2")
result = predictor.predict(peptides=[Peptide("SYFPEITHI"), Peptide("SYFPTTTHI")], alleles=[Allele("DQA1*01:01-DQB1*05:01"), Allele("HLA-DRB1*13:02")])
print result

predictor = EpitopePredictorFactory("mhcnuggets-class-1")
result = predictor.predict(peptides=[Peptide("SYFPEITHI"), Peptide("SYFPTTTHI")], alleles=[Allele("A*02:01"), Allele("A*03:01")])
print result

predictor = EpitopePredictorFactory("mhcflurry")
result = predictor.predict(peptides=[Peptide("SYFPEITHI"), Peptide("SYFPTTTHI")], alleles=[Allele("A*02:01"), Allele("A*03:01")])
print result 
```

Please verify that it's now working as intended.
Sorry for the inconveniences caused - not my standard :)

Cheers

### CODE REVIEW

**Comment by christopher-mohr** [comment]
Looks good to me! Thanks for fixing this! 👍

**Comment by b-schubert** [comment]
Thanks @Zethson ! Could you please reopen the PR and with a merge to develop so we do not mess up the dev. cycle.

Thanks again

**Comment by Zethson** [comment]
@b-schubert It's possible to change the base branch of a PR.

**Comment by Zethson** [comment]
https://github.com/FRED-2/Fred2/pull/232

**Pull request closed without merging**
